name: "Setup jq Example - Linux"

on:
  push:


jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.1

      - name: 'Check jq'
        run: |
          which jq
          jq --version
