name: test_github_actions
on:
 workflow_dispatch:  
 push:
 
jobs:
   run_shell:
    runs-on: ubuntu-latest
    steps:
     - name: get the code
       uses: actions/checkout@v3   
    
     - name: 'Setup jq'
       uses: dcarbone/install-jq-action@v1.0.1
       with:
            version: 1.6

     - name: run the script..
       run: |
            chmod +x ./migration.sh
            ./migration.sh
       shell: bash  
