name: "Setup jq Example - Linux"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: "Version of jq to install"
        default: "1.6"
      force:
        type: boolean
        required: false
        description: "Do not check for existing jq installation before continuing."
        default: false

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: '${{ inputs.version }}'
          force: '${{ inputs.force }}'
      
      - name: 'Check jq'
        run: |
          which jq
          jq --version
