name: "Setup jq Example - Linux"

on:
 workflow_dispatch:
 push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
     - name: create repo using shell on git
       run: |
         curl -u {{secrets.USERNAME}}:{{secrets.TOKEN}} https://api.github.com/user/repos -d '{"name": "HELLOWORLD", "private": true}'    
       shell: bash


        
