name: test_github_actions
on:
 workflow_dispatch:
    inputs:
        version:
          type: string
          required: false
          description: "Version of jq to install"
          default: "1.6"
        force:
          type: boolean
          required: false
          description: "Do not check for existing jq installation before continuing."
          default: false
 push:
 
jobs:
   run_shell:
    runs-on: ubuntu-latest
    steps:
     - name: get the code
       uses: actions/checkout@v3   
     - name: run the script.
       run: |
         chmod +x ./file.sh
         ./file.sh
       shell: bash

   run_migration_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: '${{ inputs.version }}'
        #  force: '${{ inputs.force }}'
      - name: run the script.
        run: |
            chmod +x ./migration.sh
            ./migration.sh
          shell: bash     

            
           
          