name: test_github_actions
on:
 workflow_dispatch:
 push:

jobs:
   run_shell:
    runs-on: ubuntu-latest
    steps:
     - name: get the code
       uses: actions/checkout@v3   
     - name: run the script.
       run: |
        chmod +x ./file.sh
        ./file.sh
       shell: bash
           
          